apiVersion: v1
kind: ConfigMap
metadata:
  name: pd-client-properties-map
  namespace: smp
data:
  pd-client.properties: |
   [
    keystore.type: pkcs12
    keystore.path: /config/smp.2018.pilot.p12
    keystore.password: peppol
    keystore.key.alias: smp.pilot
    keystore.key.password: peppol}
   ]
